- name: Setup Django + React with PostgreSQL (Postgres via Docker Compose)
  hosts: localhost
  become: true

  vars:
    project_dir: /mnt/c/Users/User/Desktop/Django-React-2022/ecommerce/backend
    backend_dir: "{{ project_dir }}"
    frontend_dir: "{{ backend_dir }}/frontend"
    venv_dir: "{{ backend_dir }}/venv"

    db_name: mydb
    db_user: myuser
    db_password: mypass
    db_host: localhost
    db_port: "5432"

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install system packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - libpq-dev
          - curl
          - build-essential
          - libjpeg-dev
          - zlib1g-dev
          - nginx
          - docker-compose
        state: present

    - name: Start PostgreSQL container with Docker Compose
      community.docker.docker_compose:
        project_src: "{{ backend_dir }}"
        restarted: true
        build: false

    - name: Wait for PostgreSQL to be ready
      wait_for:
        host: "{{ db_host }}"
        port: "{{ db_port }}"
        delay: 5
        timeout: 60

    - name: Create virtualenv if missing
      command: python3 -m venv venv
      args:
        chdir: "{{ backend_dir }}"
      when: not lookup('file', venv_dir, errors='ignore')

    - name: Upgrade pip
      command: "{{ venv_dir }}/bin/pip install --upgrade pip"
      args:
        chdir: "{{ backend_dir }}"

    - name: Install requirements
      command: "{{ venv_dir }}/bin/pip install -r requirements.txt"
      args:
        chdir: "{{ backend_dir }}"

    - name: Install Pillow
      command: "{{ venv_dir }}/bin/pip install Pillow"
      args:
        chdir: "{{ backend_dir }}"

    - name: Run Django migrations
      command: "{{ venv_dir }}/bin/python manage.py migrate"
      args:
        chdir: "{{ backend_dir }}"
      environment:
        SECRET_KEY: "your-very-secret-key"
        DB_ENGINE: django.db.backends.postgresql
        DB_NAME: "{{ db_name }}"
        DB_USER: "{{ db_user }}"
        DB_PASS: "{{ db_password }}"
        DB_HOST: "{{ db_host }}"
        DB_PORT: "{{ db_port }}"

    - name: Collect static files
      command: "{{ venv_dir }}/bin/python manage.py collectstatic --noinput"
      args:
        chdir: "{{ backend_dir }}"
      environment:
        SECRET_KEY: "your-very-secret-key"

    - name: Install Yarn
      npm:
        name: yarn
        global: yes

    - name: Install frontend deps
      command: yarn install
      args:
        chdir: "{{ frontend_dir }}"

    - name: Build React frontend
      command: yarn build
      args:
        chdir: "{{ frontend_dir }}"

    - name: Setup Nginx config
      copy:
        dest: /etc/nginx/sites-available/ecommerce
        content: |
          server {
              listen 80;
              server_name localhost;

              root /mnt/c/Users/User/Desktop/Django-React-2022/ecommerce/backend/frontend/build;
              index index.html index.htm;

              location / {
                  try_files $uri /index.html;
              }

              location /api/ {
                  proxy_pass http://127.0.0.1:8000/;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
              }

              location /static/ {
                  alias /mnt/c/Users/User/Desktop/Django-React-2022/ecommerce/backend/staticfiles/;
              }

              location /media/ {
                  alias /mnt/c/Users/User/Desktop/Django-React-2022/ecommerce/backend/media/;
              }
          }

    - name: Enable Nginx config
      file:
        src: /etc/nginx/sites-available/ecommerce
        dest: /etc/nginx/sites-enabled/ecommerce
        state: link
        force: yes

    - name: Test Nginx config
      command: nginx -t

    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
