version: "3.8"

services:
  db:
    image: postgres:16
    container_name: pg_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
